import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Container, CssBaseline } from "@mui/material";
import Header from "./header/header";
import Providers from "./providers";
import authenticated from "./auth/actions/authenticated";
import logout from "./auth/logout";
import { Roboto } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
	subsets: ["latin", "cyrillic"],
	weight: ["400", "500", "700"],
	display: "swap",
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Job Finder",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const isAuthenticated = await authenticated();

	return (
		<html lang="en">
			<body className={`${inter.className} ${roboto.className}`}>
				<Providers authenticated={isAuthenticated}>
					<CssBaseline />
					<Header logout={logout} />

					<div className="flex flex-col md:flex-row">
						<Container className={isAuthenticated ? " mt-10" : ""}>
							{children}
						</Container>
					</div>
				</Providers>
			</body>
		</html>
	);
}
